### ISSUE TITLE
Moondrop River 2 noise floor

### ISSUE THREAD

**Issue by Hill-98** [Magisk-Modules-Alt-Repo/audio-misc-settings#12]
This is not a problem with this module, but I would like to seek your advice.

I have a Moondrop River 2 USB DAC, but when I plug it into my Android phone and start playing music, there is some background noise, and nothing if it's not playing.

I also tried an app like Hiby Music, if the USB exclusive output is enabled, there will be no background noise.

I asked the Moondrop folks and they told me it's due to Android's SRC algorithm.

I tried this mod on Nokia 7 on Android 9 and the problem is still not resolved, do you know any solution?

**Comment by Hill-98** [comment]
I tested Moondrop River 2 on 4 phones respectively, namely OPPO Reno 5 Pro+ (my main phone), Nokia 7, Meizu Pro6s and Realme X7 Pro, there is no noise floor on Meizu Pro6s and Realme X7 Pro, One thing these two phones have in common is that they both use MediaTek chipsets, while OPPO and Nokia use Qualcomm chipsets. Will it be related to chipsets?

**Comment by yzyhk904** [comment]
There are two differences between MediaTek (as well as Google Tensor) and Qualcomm SoC devices. The former use the USB HAL audio driver and no DRC (Dynamic Range Control), and the latter use the hardware offload (USB tunneling) audio driver and DRC.

I think you could hear DRC distortion if your Qualcomm phones use low quality DRC. Unless so, perhaps you hear jitter distortion because my module reduces jitter effectively on the USB HAL audio driver (its USB transfer period is optimized).

You can check them if you use my another tool [USB_SampleRate_Changer](https://github.com/yzyhk904/USB_SampleRate_Changer). See its README.md.

**Comment by Hill-98** [comment]
I tried USB_SampleRate_Changer and allowed it with the `--bypass-offload` parameter. Then I also installed audio-misc-setting, but it didn't feel any obvious improvement.

**Comment by yzyhk904** [comment]
> Are DRC and SOC models related? I only tested this mod on Nokia 7 because other phones don't have Magisk and root.

All Qcomm 8 core SoC devices have been shipped with DRC on all audio outputs, but you can disable it with root.

> I tried USB_SampleRate_Changer and allowed it with the --bypass-offload parameter. Then I also installed audio-misc-setting, but it didn't feel any obvious improvement.

Um, I have no idea now.

**Comment by Hill-98** [comment]
Well, I guess changing my phone is the best solution for me. Thank you for your answer!
