### ISSUE TITLE
Equalizer app become incompatible or unusable with the module. 

### ISSUE THREAD

**Issue by Waylander05** [Magisk-Modules-Alt-Repo/audio-misc-settings#2]
I tested this on Wavelet and neutralizer. Also generic volume booster app straight up crashes.

**Comment by yzyhk904** [comment]
Did you read the README of this module? "Disabling the effects framework" is clearly described.
AudioFlinger (the OS mixer) don't load any effects configuration (e.g., /vendor/etc/audio_effects.xml). So you cannot use any equalizer, virtualizer and visualizer (except Poweramp equalizer) when enabling this module.

This is because an effects chain in the mixer generates jitter that injects very short reverb like distortion in a digital audio output.

**Comment by Waylander05** [comment]
My bad, I did read it. But I didn't know that the disabling the effects part means it disabling audio tweaks.
I used the module and still felt there's some distortion on badly mixed songs. Is it possible this module conflict with other audio mods like ainur narsil and acp?

**Comment by yzyhk904** [comment]
Did you disable the battery manager and app's battery optimization or restriction of battery usage described in the README? In my opinion, there is no use for audio effectors when disabling battery optimizations.

Anyway,  you can enable the effects framework by "extras/jitter-reducer.sh" in [USB_SampleRate_Changer](https://github.com/yzyhk904/USB_SampleRate_Changer).
Execute `sh /sdcard/USB_SampleRate_Changer/extras/jitter-reducer.sh ++effect` when you need.
