### ISSUE TITLE
Kernelsu support 

### ISSUE THREAD

**Issue by scarlettekk** [Magisk-Modules-Alt-Repo/audio-misc-settings#23]
Latest version of module and Kernelsu has error `Aborted by an incompatible Magisk variant detection.`

**Comment by yzyhk904** [comment]
I wouldn't support others except Official Magisk basically because of testing modules only on the latest released Official Magisk.

My recommendations:

1. Use Official Magisk
2. Try [Compatible Magisk-mirroring](https://github.com/yzyhk904/compatible-magisk-mirroring) patching KernelSU for installing the module. Carefully read its README!
