### ISSUE TITLE
Device is stuck booting up

### ISSUE THREAD

**Issue by Papitas30** [Magisk-Modules-Alt-Repo/audio-misc-settings#29]
After installing this module, my phone got stuck at the booting screen. The booting animation wasnt even playing. It got fixed after I managed to remove the module.
I'm using latest Magisk, Android 14 and my device is Moto G Stylus 5g 2023

**Comment by imzooel** [comment]
same here on my Poco X3 Pro (android 12). how did you fix that as it wasn't booting?

**Comment by imzooel** [comment]
> I got into safe mode and uninstalled the module

but safemode isn't available rooted poco x3 pro. i can only go to TWRP by Power+Volume up. Pressing Power+Volume down leads to Fastboot.

**Comment by imzooel** [comment]
> I got into safe mode and uninstalled the module

but safemode isn't available in my rooted poco x3 pro. i can only go to TWRP by Power+Volume up. Pressing Power+Volume down leads to Fastboot.

**Comment by yzyhk904** [comment]
Did you unplug external peripherals like a USB DAC?

I know HyperOS (supporting Dolby Atmos) repeats rebooting with a USB DAC plugged, but stops after unplugging. Its's a bug or a vulnerability of HyperOS.

I would support (test) only LineageOS and CrDroid except stock ROM's because I haven't been using stock ROM's and they are too many and too modified uniquely to support. See README.md.

If Moto G Stylus 5g 2023 has the same bug w.r.t. Dolby Atmos, unplug external peripherals first.

By the way, I'm using a HyperOS POCO device supporting Dolby Atomos temporary till some custom ROM available, and adding some workarounds for Dolby Atmos. Try this [magisk-module-audio-misc.zip](https://github.com/user-attachments/files/16064275/magisk-module-audio-misc.zip).

**Comment by yzyhk904** [comment]
> > I got into safe mode and uninstalled the module
> 
> but safemode isn't available in my rooted poco x3 pro. i can only go to TWRP by Power+Volume up. Pressing Power+Volume down leads to Fastboot.

By any chance, you don't know how to reset (initialize) phones? You can do by TWRP or "fastboot".

**Comment by yzyhk904** [comment]
I made a release candidate.  If you like, try this new module [magisk-module-audio-misc-v1.3.8.zip](https://github.com/user-attachments/files/16099991/magisk-module-audio-misc-v1.3.8.zip).

**Comment by Tommy-00-** [comment]
Hi, newbie here, the module still makes my moto g84 plus crash, i see in the code that the condition if is set to Motorola with a uppercase M and not lowecase, is it possible that's the problem?
I'll try editing it myself rn, i'll let you know if it fixes it

**Comment by yzyhk904** [comment]
Can you confirm it by executing `getprop ro.product.manufacturer` command? I picked it up from Google's official manufacture name list because of no moto device at hand.

The code would hide Moto Dolby privileged app's if they exist and hasn't been updated, and have no effect for devices having no Dolby ones.

**Comment by Tommy-00-** [comment]
I run the command on termux and i confirm it's "motorola" with a lowercase m
Tysm btw

**Comment by yzyhk904** [comment]
Can you test new module
[magisk-module-audio-misc.zip](https://github.com/user-attachments/files/16573981/magisk-module-audio-misc.zip) whether this causes bootloop or not?

**Comment by Tommy-00-** [comment]
Sure, tonight or tomorrow i'll tell you! Thank you again :)

**Comment by Tommy-00-** [comment]
It works!! No more bootloop!! And thank you cause music seem to sound better now than that awful compressed moto dolby 🤢
Great work! I'll let you know if i find any issues :)

**Comment by yzyhk904** [comment]
Thanks! I'll update its repository soon.

I'm now intensively investigating causes of "cheapie sound" about cheap audio devices and how to avoid it by digital processing. If you like, try [Resampling for cheapies](https://github.com/Magisk-Modules-Alt-Repo/resampling-for-cheapies).
