### ISSUE TITLE
SBC Dual Channel not working

### ISSUE THREAD

**Issue by sebastianjena** [Magisk-Modules-Alt-Repo/audio-misc-settings#3]
Hello! I have Pixel 6 with Derpfest ROM, I got Soundcore Life P3 earbuds which support only SBC+AAC. In theory module was successfully installed (i see increased volume steps etc) but SBC bitrate in logcat is still ~320kbps. How can I force it to work?

If the ROM needs to support it, do u maybe have the knowledge which ones support it for Android 12?

**Comment by yzyhk904** [comment]
Your ROM need to have a special SBC codec supporting the dual channel  mode, not a typical SBC codec.  There is no A12 ROM till now, but are many A11 ROM's (LineageOS 18.1, ArrowOS 11, etc.).

This module sets a property value enabling the SBC dual channel codec to raise its bitrate limit to about 600kbps only for EDR 2Mbps earphones (perhaps, entry class cheap ones. not EDR 3Mbps mid to high ones of which limit is fixed at about 550kbps).

By the way, you can raise the audio quality of your earphones if you disable "a2dp offload" in developer options because Pixel6 resamples twice (44.1kHz -> 48kHz -> 44.1kHz) in a2dp offloading. And I recommend disabling battery optimizations described in the README.

**Comment by sebastianjena** [comment]
Thanks for explanation. In theory I see commits on 12.0 branch of CRDroid, but there's only a ROM for Pixel 6 Pro for now.

Also I tried AICP and there was Dual Channel in dev settings...but it was greyed out for some reason and I couldn't choose it in any way :( Maybe you would had any idea why it's greyed out and how to unlock it..

**Comment by yzyhk904** [comment]
I wasn't aware of these recent commits because the gerrit of LineageOS sources showed dual channel patches in a review phase.

The dual channel mode can be effective only in the AOSP bluetooth stack, not in other stacks. So you need to disable "a2dp hardware offload" in dev settings on some devices (typically using a Snapdragon SoC, e.g., Pixel5, Pixel4, etc.). Maybe Pixel6's are included.

**Comment by sebastianjena** [comment]
Nice hint thank you. One more question: how does your module affect LDAC? (96kHz is used then)

**Comment by yzyhk904** [comment]
I recommend using its 44.1kHz 32bit mode with jitter-reducer.sh in my another tool [USB_SampleRate_Changer](https://github.com/yzyhk904/USB_SampleRate_Changer).
(needless to say, to be DRC free and without a2dp offloading to avoid multiple resampling)

The audio quality of bluetooth a2dp is affected by jitter at the transmitter side very much.
Don't forget disabling a battery manager and battery optimizations of app's described in the README.
