### ISSUE TITLE
Support For Apatch 

### ISSUE THREAD

**Issue by hopez13** [Magisk-Modules-Alt-Repo/audio-misc-settings#34]
https://github.com/bmax121/APatch

please add support for it 
it's better at hiding root

**Comment by yzyhk904** [comment]
Since I would test my modules only on latest LineageOS and crDroid with official Magisk, I wouldn't support other combinations directly. However, if your environment is compatible to them, my modules should run correctly on it.

You should request the dev. of APatch to make it to be compatible to official Magisk with restpect to Magisk modules.

By the way, I don't think APatch is better at hiding root in real use.

**Comment by yzyhk904** [comment]
It isn't correct. It refers possibly modified files, not original ones!

If you like to use this module any way, use [Compatible magisk mirroring](https://github.com/Magisk-Modules-Alt-Repo/compatible-magisk-mirroring)! See its README in detail.

**Comment by yzyhk904** [comment]
See [Compatible Magisk Mirroring](https://github.com/Magisk-Modules-Alt-Repo/compatible-magisk-mirroring)!

**Comment by yzyhk904** [comment]
I forgot to mention that some apps might detect Magisk by mistake if you used "Compatible Magisk Mirroring". Probably they detect "sku-magisk" script in /data/adm/ap/bin which it placed.

And the sound issue is caused by hyperOS. Use LineageOS or like.

**Comment by yzyhk904** [comment]
It isn't enough. Targeted files under /vendor shall be modified by its previous version already installed when updating a module. You cannot update such modules correctly if referring files under /vendor in them.

Some popular modules supporting KernelSU and APatch have such a bug within them.
