### ISSUE TITLE
Nice mod

### ISSUE THREAD

**Issue by NPina** [Magisk-Modules-Alt-Repo/audio-misc-settings#4]
I like this mod, I can spot the the difference rather way, but it was a bug or problem, at list for me.
Everything works great except one thing.
Then I go calling somebody it switch off immediately from 4G aka "LTE" to 3G and that turn off voice quality enhancement that only 4G was, I can still listen good but in other side of the call not they say it's not the same voice quality, with this mod deactivate the call stays in 4G.

**Comment by yzyhk904** [comment]
I think your phone app cannot use "automatic gain control" and "echo canceler", and wrongly switches so because "audio-misc-settings" disables the effects framework to stop jitter distortion from the framework. Try other phone apps as they wouldn't use such effects but may use 4G.

**Comment by NPina** [comment]
I use one AOSP OS A11 api30 it comes with all native apps of AOSP, my dialer app is "com.android.dialer v23.0" exact same as Lineage OS was, I already try the latest Google Phone app and same happens, then I press the call button my phone rapidly switch from 4G to 3G turning off with it this feature [(4G Calling) "Use 4G services to improve voice and other communications (recommended)"].
Now I ask this behavior are only happening to me, your phone stays in 4G then you use this module?

**Comment by yzyhk904** [comment]
I haven't heard such issues till now. My SIM is for LTE only, so there is no such fallbacks and I can make calls. Since audio-misc-settings is a simple module setting only android audio configuration values, there is no way.

If you like, try "extras/jitter-reducer.sh" with "++effect" option in [USB_SampleRate_Changer](https://github.com/yzyhk904/USB_SampleRate_Changer). This command enables the effects framework again (but would generate jitter distortion from the framework).

**Comment by NPina** [comment]
Okay, looks like this is only for me, thanks for you try to help me.
I will try what are saying.
Compliments

**Comment by NPina** [comment]
Hello, with last update that problem I has having are fixed now.
Thanks

**Comment by yzyhk904** [comment]
Um, I haven't done anything for phones. What I've done is reducing the computational cost of resampling while keeping a mastering quality of resampling. I guess the cause is stuttering by high cost resampling.
