### ISSUE TITLE
Front camera conflict

### ISSUE THREAD

**Issue by GeorgesGraire** [Magisk-Modules-Alt-Repo/audio-misc-settings#5]
On the POCO F2 Pro, with a front cam module that pops out, it doesn't work anymore when this module is installed. When uninstalled it goes back to working normally.

After playing with it, I noticed the sensor works since I can see some light passing through. It's just that the module doesn't pop out.

**Comment by yzyhk904** [comment]
I guess the module is a king of Xiaomi's extras integrated module including settings for adjusting equalizers, virtualizers, visualizers, etc., like Xiaomi Parts on tablets. In this case, the cause is to disable the effects framework of the OS mixer.

Try "extras/jitter-reducer.sh" with "++effect --status" options in [USB_SampleRate_Changer](https://github.com/yzyhk904/USB_SampleRate_Changer). This enables the effect framework on the fly. Then you may use the module that pops out.
